name: bibleplan
description: Biblical App.

publish_to: 'none' 

version: 3.0.1+40

environment:
  sdk: '>=3.5.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  cupertino_icons: ^1.0.5
  path_provider: ^2.0.8
  shared_preferences: ^2.0.12
  collection: ^1.14.11
  font_awesome_flutter: ^10.9.1
  http: ^0.13.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  firebase_analytics: ^12.0.3
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  share_plus: ^12.0.1
  firebase_core: ^4.2.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/data/
  - assets/data/pt/
  - assets/data/es/
  - assets/data/en/
  - assets/data/fr/
  - assets/data/zh-CN/
  - assets/images/